<?php
/**
 * AtrybutyTowaruApi
 * PHP version 5
 *
 * @category Class
 * @package  OptimaClientApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EcOptimaApi
 *
 * Proste Api do Optimy
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace OptimaClientApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Message\Request;
use GuzzleHttp\Stream;

use GuzzleHttp\RequestOptions;
use OptimaClientApi\ApiException;
use OptimaClientApi\Configuration;
use OptimaClientApi\HeaderSelector;
use OptimaClientApi\ObjectSerializer;

/**
 * AtrybutyTowaruApi Class Doc Comment
 *
 * @category Class
 * @package  OptimaClientApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AtrybutyTowaruApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation pobierzAtrybut
     *
     * Pobieranie atrybutów
     *
     * @param  int $twr_id Id Towaru dla którego pobieramy atrybut (required)
     * @param  string $attr_kod Kod Atrybutu (required)
     *
     * @throws \OptimaClientApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OptimaClientApi\Model\AtrybutTowaruItem
     */
    public function pobierzAtrybut($twr_id, $attr_kod)
    {
        list($response) = $this->pobierzAtrybutWithHttpInfo($twr_id, $attr_kod);
        return $response;
    }

    /**
     * Operation pobierzAtrybutWithHttpInfo
     *
     * Pobieranie atrybutów
     *
     * @param  int $twr_id Id Towaru dla którego pobieramy atrybut (required)
     * @param  string $attr_kod Kod Atrybutu (required)
     *
     * @throws \OptimaClientApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OptimaClientApi\Model\AtrybutTowaruItem, HTTP status code, HTTP response headers (array of strings)
     */
    public function pobierzAtrybutWithHttpInfo($twr_id, $attr_kod)
    {
        $returnType = '\OptimaClientApi\Model\AtrybutTowaruItem';
        $request = $this->pobierzAtrybutRequest($twr_id, $attr_kod);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OptimaClientApi\Model\AtrybutTowaruItem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation pobierzAtrybutAsync
     *
     * Pobieranie atrybutów
     *
     * @param  int $twr_id Id Towaru dla którego pobieramy atrybut (required)
     * @param  string $attr_kod Kod Atrybutu (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function pobierzAtrybutAsync($twr_id, $attr_kod)
    {
        return $this->pobierzAtrybutAsyncWithHttpInfo($twr_id, $attr_kod)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation pobierzAtrybutAsyncWithHttpInfo
     *
     * Pobieranie atrybutów
     *
     * @param  int $twr_id Id Towaru dla którego pobieramy atrybut (required)
     * @param  string $attr_kod Kod Atrybutu (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function pobierzAtrybutAsyncWithHttpInfo($twr_id, $attr_kod)
    {
        $returnType = '\OptimaClientApi\Model\AtrybutTowaruItem';
        $request = $this->pobierzAtrybutRequest($twr_id, $attr_kod);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'pobierzAtrybut'
     *
     * @param  int $twr_id Id Towaru dla którego pobieramy atrybut (required)
     * @param  string $attr_kod Kod Atrybutu (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function pobierzAtrybutRequest($twr_id, $attr_kod)
    {
        // verify the required parameter 'twr_id' is set
        if ($twr_id === null || (is_array($twr_id) && count($twr_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $twr_id when calling pobierzAtrybut'
            );
        }
        // verify the required parameter 'attr_kod' is set
        if ($attr_kod === null || (is_array($attr_kod) && count($attr_kod) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $attr_kod when calling pobierzAtrybut'
            );
        }

        $resourcePath = '/atrybuty-towaru/towary/{TwrId}/atrybut-towaru/{AttrKod}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($twr_id !== null) {
            $resourcePath = str_replace(
                '{' . 'TwrId' . '}',
                ObjectSerializer::toPathValue($twr_id),
                $resourcePath
            );
        }
        // path params
        if ($attr_kod !== null) {
            $resourcePath = str_replace(
                '{' . 'AttrKod' . '}',
                ObjectSerializer::toPathValue($attr_kod),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ustawAtrybut
     *
     * Ustawianie atrybutu towaru.
     *
     * @param  \OptimaClientApi\Model\AtrybutTowaruItem[] $body Wartość którą ustawiamy atrybutowi (required)
     *
     * @throws \OptimaClientApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function ustawAtrybut($body)
    {
        $this->ustawAtrybutWithHttpInfo($body);
    }

    /**
     * Operation ustawAtrybutWithHttpInfo
     *
     * Ustawianie atrybutu towaru.
     *
     * @param  \OptimaClientApi\Model\AtrybutTowaruItem[] $body Wartość którą ustawiamy atrybutowi (required)
     *
     * @throws \OptimaClientApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function ustawAtrybutWithHttpInfo($body)
    {
        $returnType = '';
        $request = $this->ustawAtrybutRequest($body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation ustawAtrybutAsync
     *
     * Ustawianie atrybutu towaru.
     *
     * @param  \OptimaClientApi\Model\AtrybutTowaruItem[] $body Wartość którą ustawiamy atrybutowi (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ustawAtrybutAsync($body)
    {
        return $this->ustawAtrybutAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ustawAtrybutAsyncWithHttpInfo
     *
     * Ustawianie atrybutu towaru.
     *
     * @param  \OptimaClientApi\Model\AtrybutTowaruItem[] $body Wartość którą ustawiamy atrybutowi (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ustawAtrybutAsyncWithHttpInfo($body)
    {
        $returnType = '';
        $request = $this->ustawAtrybutRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ustawAtrybut'
     *
     * @param  \OptimaClientApi\Model\AtrybutTowaruItem[] $body Wartość którą ustawiamy atrybutowi (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function ustawAtrybutRequest($body)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling ustawAtrybut'
            );
        }

        $resourcePath = '/atrybuty-towaru/towary';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
