<?php
/**
 * IloscItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OptimaClientApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EcOptimaApi
 *
 * Proste Api do Optimy
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace OptimaClientApi;

/**
 * IloscItemTest Class Doc Comment
 *
 * @category    Class
 * @description IloscItem
 * @package     OptimaClientApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IloscItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IloscItem"
     */
    public function testIloscItem()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "twr_id"
     */
    public function testPropertyTwrId()
    {
    }

    /**
     * Test attribute "mag_id"
     */
    public function testPropertyMagId()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "ilosc"
     */
    public function testPropertyIlosc()
    {
    }

    /**
     * Test attribute "wartosc"
     */
    public function testPropertyWartosc()
    {
    }

    /**
     * Test attribute "braki"
     */
    public function testPropertyBraki()
    {
    }

    /**
     * Test attribute "rezerwacje"
     */
    public function testPropertyRezerwacje()
    {
    }

    /**
     * Test attribute "zamowienia"
     */
    public function testPropertyZamowienia()
    {
    }
}
