<?php
/**
 * AtrybutTowaruItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  OptimaClientApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EcOptimaApi
 *
 * Proste Api do Optimy
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace OptimaClientApi\Model;

use \ArrayAccess;
use \OptimaClientApi\ObjectSerializer;

/**
 * AtrybutTowaruItem Class Doc Comment
 *
 * @category Class
 * @package  OptimaClientApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AtrybutTowaruItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AtrybutTowaruItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
'twr_id' => 'int',
'kod' => 'string',
'nazwa' => 'string',
'wartosc' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int64',
'twr_id' => 'int64',
'kod' => null,
'nazwa' => null,
'wartosc' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'Id',
'twr_id' => 'TwrId',
'kod' => 'Kod',
'nazwa' => 'Nazwa',
'wartosc' => 'Wartosc'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'twr_id' => 'setTwrId',
'kod' => 'setKod',
'nazwa' => 'setNazwa',
'wartosc' => 'setWartosc'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'twr_id' => 'getTwrId',
'kod' => 'getKod',
'nazwa' => 'getNazwa',
'wartosc' => 'getWartosc'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['twr_id'] = isset($data['twr_id']) ? $data['twr_id'] : null;
        $this->container['kod'] = isset($data['kod']) ? $data['kod'] : null;
        $this->container['nazwa'] = isset($data['nazwa']) ? $data['nazwa'] : null;
        $this->container['wartosc'] = isset($data['wartosc']) ? $data['wartosc'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['twr_id'] === null) {
            $invalidProperties[] = "'twr_id' can't be null";
        }
        if ($this->container['kod'] === null) {
            $invalidProperties[] = "'kod' can't be null";
        }
        if ($this->container['wartosc'] === null) {
            $invalidProperties[] = "'wartosc' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets twr_id
     *
     * @return int
     */
    public function getTwrId()
    {
        return $this->container['twr_id'];
    }

    /**
     * Sets twr_id
     *
     * @param int $twr_id twr_id
     *
     * @return $this
     */
    public function setTwrId($twr_id)
    {
        $this->container['twr_id'] = $twr_id;

        return $this;
    }

    /**
     * Gets kod
     *
     * @return string
     */
    public function getKod()
    {
        return $this->container['kod'];
    }

    /**
     * Sets kod
     *
     * @param string $kod kod
     *
     * @return $this
     */
    public function setKod($kod)
    {
        $this->container['kod'] = $kod;

        return $this;
    }

    /**
     * Gets nazwa
     *
     * @return string
     */
    public function getNazwa()
    {
        return $this->container['nazwa'];
    }

    /**
     * Sets nazwa
     *
     * @param string $nazwa nazwa
     *
     * @return $this
     */
    public function setNazwa($nazwa)
    {
        $this->container['nazwa'] = $nazwa;

        return $this;
    }

    /**
     * Gets wartosc
     *
     * @return string
     */
    public function getWartosc()
    {
        return $this->container['wartosc'];
    }

    /**
     * Sets wartosc
     *
     * @param string $wartosc wartosc
     *
     * @return $this
     */
    public function setWartosc($wartosc)
    {
        $this->container['wartosc'] = $wartosc;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
