<?php
/**
 * AtrybutyTowaruApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OptimaClientApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EcOptimaApi
 *
 * Proste Api do Optimy
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace OptimaClientApi;

use OptimaClientApi\Configuration;
use OptimaClientApi\ApiException;
use OptimaClientApi\ObjectSerializer;

/**
 * AtrybutyTowaruApiTest Class Doc Comment
 *
 * @category Class
 * @package  OptimaClientApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AtrybutyTowaruApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for pobierzAtrybut
     *
     * Pobieranie atrybutów.
     *
     */
    public function testPobierzAtrybut()
    {
    }

    /**
     * Test case for ustawAtrybut
     *
     * Ustawianie atrybutu towaru..
     *
     */
    public function testUstawAtrybut()
    {
    }
}
