<?php
/**
 * MagazynApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OptimaClientApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EcOptimaApi
 *
 * Proste Api do Optimy
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace OptimaClientApi;

use OptimaClientApi\Configuration;
use OptimaClientApi\ApiException;
use OptimaClientApi\ObjectSerializer;

/**
 * MagazynApiTest Class Doc Comment
 *
 * @category Class
 * @package  OptimaClientApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MagazynApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for pobierzDefMagazyny
     *
     * Pobiera listę magazynów.
     *
     */
    public function testPobierzDefMagazyny()
    {
    }

    /**
     * Test case for pobierzIloscTowaru
     *
     * Pobieranie stanu magazynowego.
     *
     */
    public function testPobierzIloscTowaru()
    {
    }

    /**
     * Test case for pobierzStanMagazynowyDlaTowaru
     *
     * Pobiera stan magazynowy towaru.
     *
     */
    public function testPobierzStanMagazynowyDlaTowaru()
    {
    }

    /**
     * Test case for pobierzStanyMag
     *
     * Pobieranie stanu magazynowego.
     *
     */
    public function testPobierzStanyMag()
    {
    }

    /**
     * Test case for pobierzStanyMagPost
     *
     * Pobieranie stanu magazynowego.
     *
     */
    public function testPobierzStanyMagPost()
    {
    }
}
